services:
  web:
    image: ${REGISTRY}/${IMAGE_NAME}:latest
    container_name: ${GITHUB_EVENT_REPOSITORY_NAME}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: always
